### ISSUE TITLE
mkdir: cannot create directory '': No such file or directory

### ISSUE THREAD

**Issue by tfdetang** [JustinChristensen/trinitycore-dockerfile#1]
after run `export TRINITYCORE_VERSION="3.3.5"
docker build -t trinitycore-base --build-arg TRINITYCORE_VERSION base`.  I got a `mkdir: cannot create directory '': No such file or directory` error.

**Comment by JustinChristensen** [comment]
Please paste the full output. Also, is your present working directory the cloned repo?

**Comment by tfdetang** [comment]
yes, my working directory is the cloned repo.

before step 12/14, everything work just fine
```
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 7fdcea82246f
 ---> e9755f9803cc
Step 11/14 : WORKDIR ${TRINITYCORE_USER_HOME}
 ---> Running in 591a7bee022e
Removing intermediate container 591a7bee022e
 ---> 8053a5cd8207
Step 12/14 : RUN echo "Pulling down version ${TRINITYCORE_VERSION} of TrinityCore..." && curl -o TrinityCore.tar.gz -sL "https://github.com/TrinityCore/TrinityCore/tarball/${TRINITYCORE_VERSION}" && mkdir -p "${TRINITYCORE_SOURCE_DIR}" && tar -xvzf TrinityCore.tar.gz -C "${TRINITYCORE_SOURCE_DIR}" --strip-components=1
 ---> Running in e47d5bb34862
Pulling down version 3.3.5 of TrinityCore...
mkdir: cannot create directory '': No such file or directory
The command '/bin/sh -c echo "Pulling down version ${TRINITYCORE_VERSION} of TrinityCore..." && curl -o TrinityCore.tar.gz -sL "https://github.com/TrinityCore/TrinityCore/tarball/${TRINITYCORE_VERSION}" && mkdir -p "${TRINITYCORE_SOURCE_DIR}" && tar -xvzf TrinityCore.tar.gz -C "${TRINITYCORE_SOURCE_DIR}" --strip-components=1' returned a non-zero code: 1
```

**Comment by JustinChristensen** [comment]
It seemingly thinks TRINITYCORE_SOURCE_DIR is not defined. Which version of Docker are you on?

Post the output of `docker --version`. 

Also, thank you for trying to get this working!

**Comment by tfdetang** [comment]
Docker version 18.09.6 ； I have replaced the variables to a fixed arg, hope it could work.  Thank you for sharing your work & all replies!

**Comment by JustinChristensen** [comment]
Well the Dockerfile is correct. I'm not in front of my laptop at the moment. Try updating docker to the latest version. I'll install the version you're on tonight or tomorrow morning and do some debugging.

**Comment by JustinChristensen** [comment]
Using Docker version 18.09.2, build 6247962 of Docker I was able to get it to build trinitycore-base just fine. Did you do something special with your docker configuration, or did you edit the Dockerfile before running in any way?

The specific error you're getting is saying that TRINITYCORE_SOURCE_DIR is not defined (mkdir -p is trying to create the directory ''), which is of course not true, because it's defined on line 9 as https://github.com/JustinChristensen/trinitycore-dockerfile/blob/master/base/Dockerfile#L9.

**Comment by tfdetang** [comment]
Indeed, I saw everything has dfined in dockerfile. The echo line also can show arg variables. The only problem is "mkdir -p ${xxxx_DIR}".   I think it could be a Docker or  OS error.

**Comment by JustinChristensen** [comment]
What OS/Version are you on?

**Comment by JustinChristensen** [comment]
Let me know if you want to keep this open. If I don't hear back from you within a couple of days I'm going to close this as "Cannot Reproduce"

**Comment by tfdetang** [comment]
I think this issue can be closed. The error was on a highly customized linux (synology nas). After switch to an centos system, everything work great.

**Comment by JustinChristensen** [comment]
You were able to follow the instructions and get everything running? Any feedback?

**Comment by tfdetang** [comment]
I'm trying.  docker-compose seems bring everything up, but authserver log 
```
Checking database connection...,
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115),
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115),
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115),
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115),
```

**Comment by tfdetang** [comment]
It's harder than I expect. After handle the database issue, world server logs shows some file miss. I think it could be I have a wrong client downloaded. Is there any client version requirements?

**Comment by JustinChristensen** [comment]
Post logs please

**Comment by tfdetang** [comment]
Here is the logs:
```
99% [Map 000] Building tile [43,29],
[Map 000] [43,29]:  Building movemap tiles...,
[Map 000] [43,29]:  Building navmesh tile...,
[Map 000] [43,29]:  Adding tile to navmesh...,
[Map 000] [43,29]:  Writing to file...,
99% [Map 000] Building tile [43,30],
99% [Map 000] Building tile [43,31],
99% [Map 000] Building tile [43,32],
99% [Map 000] Building tile [43,33],
99% [Map 000] Building tile [43,34],
99% [Map 000] Building tile [44,25],
99% [Map 000] Building tile [44,26],
[Map 000] [44,26]:  Building movemap tiles...,
[Map 000] [44,26]:  Building navmesh tile...,
[Map 000] [44,26]:  Adding tile to navmesh...,
[Map 000] [44,26]:  Writing to file...,
99% [Map 000] Building tile [44,27],
99% [Map 000] Building tile [44,28],
99% [Map 000] Building tile [44,29],
99% [Map 000] Building tile [44,30],
[Map 000] Complete!,
Finished. MMAPS were built in 5024480 ms!,
Checking database connection...,,
),
10.4.7-MariaDB-1:10.4.7+maria~bionic,
Downloading world database...,
Given url: https://github.com/TrinityCore/TrinityCore/releases/download/TDB335.19081/TDB_full_world_335.19081_2019_08_16.7z,
Creating databases...,
ERROR 1007 (HY000) at line 3: Can't create database 'world'; database exists,
Creating and populating tables for characters...,
Running updates for characters...,
Creating and populating tables for world...,
Running updates for world...,
Setting database configuration from env...,
Map file '/usr/local/data/maps/0013339.map' does not exist!,
Please place MAP-files (*.map) in the appropriate directory (/usr/local/data/maps/), or correct the DataDir setting in your worldserver.conf file.,
Unable to load critical files - server shutting down !!!,
```

**Comment by JustinChristensen** [comment]
What commands did you use to run the containers?

**Comment by JustinChristensen** [comment]
Also, paste the output of `docker-compose run -it --entrypoint=bash worldserver ls -l /usr/local/data`
