### ISSUE TITLE
Question - other versions like latest BFA

### ISSUE THREAD

**Issue by Karnith** [JustinChristensen/trinitycore-dockerfile#2]
Sorry, you didn't have any template for questions so I'm using this one.
I see you've done what I was just thinking of doing, this is great. I also see that you say this only supports 3.3.5... Is there an issue with pulling master and compiling from it? the tarball location should be https://github.com/TrinityCore/TrinityCore/tarball/master and if I read your code correctly there would only need to be some minor changes to it for auth, base and world. Is this an accurate assessment? I'd like to help out if you don't mind..

**Comment by JustinChristensen** [comment]
I haven't taken the time to evaluate how much work would be needed for this to work with the TrinityCore master branch. The intent for this project was to show off what Docker is capable of, and then to try and get the TrinityCore maintainers excited about what it can do for the project. And then, ideally, get it expanded and merged with TrinityCore.

https://github.com/TrinityCore/TrinityCore/issues/23741

Unfortunately that went over like a lead balloon, and this ended up just being a fun way to kill a couple of days.

If you want to extend this I can either:
1. Give you write access to this repository or
2. You can fork this and continue on with your changes

Let me know what you would prefer.

**Comment by Karnith** [comment]
I'll fork it and investigate. I'm also contemplating on creating a nodejs emulator based on trinitycore source, [moleculerjs](https://moleculer.services/) (micro-service framework) and typescript.

**Comment by JustinChristensen** [comment]
Cool. Good luck! Close this if you're satisfied.
