### ISSUE TITLE
Not an issue, per. se.

### ISSUE THREAD

**Issue by LunarEngineer** [JustinChristensen/trinitycore-dockerfile#3]
**System Details**
Immaterial

**Problem**
I need functionality to build a local branch.

**Logs**
```
No logs generated
```

Good morning! I am about to steal your work, change a thing or two, and then I wanted to know if you would rather have that code *here*, or not.

The change I am going to make is to allow pointing at a *directory* instead of a branch for the build arguments, so I can tinker around in the code and rebuild locally.

That will allow me to branch and then install from a local branch.

**Comment by JustinChristensen** [comment]
Go for it. I'm not planning on maintaining this unless I see some forward progress from the TrinityCore maintainers on that issue I created. 

Close this issue if that answered your question.

**Comment by LunarEngineer** [comment]
It did, thanks. I'm just sorry that the Trinity devs aren't very friendly or willing to work outside their comfort zone.
